export const SKILLS = [
    "Generative AI",
    "TypeScript/JavaScript",
    "Python",
    "React/Next.js",
    "Terraform",
    "Azure",
    "AWS",
    "GCP",
    "Java",
    "Docker",
    "Kubernetes",
    "PostgreSQL",
    "Machine Learning",
    "git",
    "DevOps",
    "Quarkus",
    "Angular",
    "Spring Boot",
    "Databricks",
    "SQL",
    "Cursor",
    "LangChain",
    "LlamaIndex",
    "LangGraph",
    "Semantic Kernel",
    "Vector Databases",
    "Agentic RAG",
    "Task Automation Agents",
    "Autonomous Agents",
  ];